site_name: uvault documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections

plugins:
  - search
  - mkdocstrings

nav:
  - Quickstart: index.md
  - Tutorials / How-To: how-to.md
  - Reference: reference.md
