[project]
site_name = "uvault documentation"
nav = [
    { "Quickstart" = "index.md" },
    { "Tutorials / How-To" = "how-to.md" },
    { "Reference" = "reference.md" },
    { "Contributing" = "contributing.md" }
]

[project.theme]
name = "material"
features = [
    "navigation.tabs",
    "navigation.sections"
]

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/petrus-v/uvault"
name = "uvault on GitHub"

[[project.extra.social]]
icon = "fontawesome/brands/python"
link = "https://pypi.org/project/uvault/"
name = "uvault on PyPI"

[project.plugins.search]
[project.plugins.mkdocstrings]
